version: "3"

services:

  commander_local:
    build:
      context: ./Docker_dual_system/local
      dockerfile: Dockerfiles/Commander.Dockerfile
    image: drone-docker-testing/commander:latest
    network_mode: host
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    # env_file:
    #   - ./Docker_dual_system/common.env
    #   - ./Docker_dual_system/sim.env
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri/card0:/dev/dri/card0
    entrypoint: /container-start.sh
    stdin_open: true
    tty: true
